# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 301519bd9eb589f9a52bde122c051a02201b1317b3699d2d97fdf9af242b8697f2e3491f9f55fc7d6b28058126a888a0239f5a7c4ba8300a1593b001b440b4c0

test:
  secret_key_base: 5a13cbadc3bac03ce471ee173badd714cee491f5a5af72382db959e8068114e848d0e17a7b5876a7a12b1f058994d82461a9761fb8a9ab95a7d76ecf39193c88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
